### ISSUE TITLE
waveSharp bug/error : failure to open a TIFF file saved from RegiStax 6

### ISSUE THREAD

**Issue by lmatias2** [CorBer/waveSharp#32]
**Describe the bug**
If a file previously processed with RegiStax 6 is dragged and dropped into waveSharp you get the following screen:
<img width="248" alt="image" src="https://github.com/CorBer/waveSharp/assets/146407235/e65afadb-fff6-4e8b-8707-f3d76ccf4c5c">
If you try to open it from the File Menu or the open icon you get this instead:
<img width="143" alt="image" src="https://github.com/CorBer/waveSharp/assets/146407235/abd66246-f25f-4ac5-b6c7-81ec7d36fd52">
with no further explanation.
**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. start waveSharp
2. Drag or open the image in the attached zip file:
[2022-09-23-001122-Jupiter-Bin1 91.8F_pip50_lapl8_ap919_Drizzle15_wav.zip](https://github.com/CorBer/waveSharp/files/12882588/2022-09-23-001122-Jupiter-Bin1.91.8F_pip50_lapl8_ap919_Drizzle15_wav.zip)
**Expected behavior**
I will expect the tool to open it or a better explanation in the popup window as to why it could not be opened.

**Operating system and version**
 - OS: Microsoft Windows 11 Home
 - Version: 10.0.22621
 - Processor: 13th Gen Intel (R) Core (TM) i9-13900K, 3000 MHz, 24 Cores(s), 32 Logical Processors
 - RAM: 64GB
 - Graphics: NVIDIA GeForce RTX 4090

**Additional context**

**Comment by CorBer** [comment]
Hi,

I can at least confirm that this file does give problems when loading. This is NOT related to drag and drop but also happens when you try to select the file using the image-selection dialog. A preview of the file is NOT presented and the system halts. So this must be clearly a specific TIFF issue, the routine I use to read TIFF is a built-in routine which does not give a clear error-message. I will :
a) see if I can catch the error before it happens (currently the system can freeze when selecting the file)
b) see if I can change the TIFF library.

For both of this options it is unclear if I can repair/prevent them to happen. TIFF is a format that has many "dialects" and not all libraries except all TIFF files.

Thanks for reporting and clearly documenting.

cheers
Cor

**Comment by CorBer** [comment]
A) is arranged, both in drag&drop and when using the normal dialog I am catching the error before it can freeze the system.
B) seems to be less likely. 

This seems to point towards a TIFF file (from RegiStax) that is not formatted as the current Freepascal library is expecting. Might be that I have programmed that wrong in the past.

For now, the best solution - to avoid this - is to use PNG as the default format. That is perfectly capapable of storing 16bit data per RGB channel and is a lot better standardized. 
I will still see if I can get this to work.

cheers
Cor

**Comment by lmatias2** [comment]
Hi Cor.

Now I am getting:
<img width="147" alt="image" src="https://github.com/CorBer/waveSharp/assets/146407235/d3fc438a-2608-4135-a0b3-ccc6dc6c106b">
consistently which is better.
RS6 is able to open it. Do you have a clue of what's different?

**Comment by CorBer** [comment]
Hi,

It has to do with the way the image is stored inside the TIFF file and the header data. The header data are seen (your first image shows that) as inconsistent in terms of samples per pixels. 
I am still seeing if I can find a way around that as the file you shared is read - without any message - by most other software. 

cheers
Cor

**Comment by CorBer** [comment]
I am one step deeper into this. Ive made a local copy of the routine that reads tiff-files (the freepascal version is from 2012 so not updated regularly). This allows me to track/trace what needs to be done if a TIFF comes in with this type of "metadata". In short, the file tells it has one layer but that should have been 3 since its an RGB file. ***** WORK IN PROGRESS *****

**Comment by CorBer** [comment]
![image](https://github.com/CorBer/waveSharp/assets/1329760/58a186a4-3116-496d-9b6a-5440c27f4bed)

Managed to get your image in but with a lot of tweaking so this isnt a solution yet !

**Comment by CorBer** [comment]
Next up I will test a set of TIFF files with the new routines using different setups (with/without alpha, only gray etc) to see if they at least dont stop the program.

**Comment by CorBer** [comment]
Try this version:
https://github.com/CorBer/waveSharpDevelopment/releases/download/v0.3start/waveSharp_V03_08_WIN64.zip

Be aware that this will need a very good test using many different types of TIFF before I am certain we can keep this codesection.

**Comment by CorBer** [comment]
https://github.com/CorBer/waveSharpDevelopment/releases/download/v0.3start/waveSharp_V03_08b_WIN64.zip

**Comment by lmatias2** [comment]
What about if sample the data itself to determine its configuration and then override the header information?

Regards,

Luis A Matías
***@***.***

**Comment by CorBer** [comment]
Hi,

I do not want to "touch" original files from users. I rather solve the issues with those files.

Cor

**Comment by CorBer** [comment]
And I rather would know if the current initial solution is working as planned. Please test that first.

**Comment by lmatias2** [comment]
It does work with Windows

Regards,

Luis A Matías
***@***.***

**Comment by CorBer** [comment]
Good. That means I can now simply wait for the other testers to confirm this. I will therefore close this issue and mark it as a feature for the next update. Thanks for reporting and testing.

cheers
Cor

**Comment by lmatias2** [comment]
Welcome

Regards,

Luis A Matías
***@***.***
