### ISSUE TITLE
Wavesharp has access violation when clicking on the green image box for resizing

### ISSUE THREAD

**Issue by cfbradshaw** [CorBer/waveSharp#38]
When I clicked on the image size square, I got an access violation.  These violations appear occasionally with different input characteristics.  Resizing also causes these violations.  I'm using Ubuntu 22.04 linux with current Gnome.
![Screenshot from 2023-11-23 14-10-09](https://github.com/CorBer/waveSharp/assets/109422209/2f3b9a86-da8a-48e9-9114-a8f8a308bfcf)

**Comment by CorBer** [comment]
Hi 

The image looks very small, what are the dimensions ? What looks like happening is the "ROI" is covering part outside the image. I think we never tested very small images.

Cor

**Comment by cfbradshaw** [comment]
288x233 pixels!

Charlie

**Comment by CorBer** [comment]
OK. Thats not that small. I have tested 200x200 without issues. When your zip eventually arrives I will have a look at what causes this.

Cor

**Comment by CorBer** [comment]
OK. I have had a look at your zip file. Turns out that the images in the batch belong to two groups with different sizes. That can (wont always happen) create errors. Thanks for reporting this. I will see if I can improve the code to prevent the error. But the advice is simple, dont make the images in a batch very different in terms of dimensions.
